name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/**"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY_URL: ${{ vars.ECR_REPOSITORY_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::968185520468:role/github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ env.ECR_REPOSITORY_URL }}:${{ github.sha }}

      - name: Set image tag env var
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Update Helm chart values
        run: |
          # Update the image.tag value in the Helm chart values.yaml file
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" helm/adc-app/values.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update image to ${{ github.sha }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-image-${{ github.sha }}
          delete-branch: true
          title: "Update image to ${{ github.sha }}"
          body: |
            This PR updates the image tag to the latest commit SHA:
            - ${{ github.sha }}

            Automatically generated by GitHub Actions.
          labels: |
            automated-pr
            image-update
          draft: false

      - name: Enable Auto-merge
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
